### PR TITLE
Added Basic Auth

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Adds basic auth (I really don't like the syntax of the with)

### CODE REVIEW

**Comment by mwhipple** [comment]
Thanks! This should have a corresponding doc update also, I can throw a PR together against yours.

> (I really don't like the syntax of the with)

What do you mean? Is this related to:
```gherkin
And expected GET sent to `/query` with 
```
I don't think that `with` should be there, from what I can tell it just happens to work because that regex isn't anchored.

**Comment by Lewiscowles1986** [comment]
I can write up the docs. 

The quoted-text was from another example. It seemed to fail in the right places, then it went green in the right places. I may have misunderstood this.

**Comment by Lewiscowles1986** [comment]
Using vscode plugin I was able to generate the following doc preview
Screenshot of documentation preview

**Review by mwhipple — APPROVED** [review]
Looks great, thanks! I added a newline to one of the files, removing that `with` might be nicer later but those features could probably use some more general cleanup. I'll look to cut a `0.9` release with this by the beginning of next week before I merge the other open PR.

**Comment by mwhipple** [comment]
FYI: released as part of v0.9.0

**Pull request merged**
